title: Home

menu:
  - title: Biography
    url: /bio.html
  - title: 研究経歴
    url: /bio_j.html
  
  - title: Publications
    url: /pub.html
  - title: 論文業績
    url: /pub_j.html

  - title: Projects
    url: /proj.html

  # - title: 
  #   url: 
  # - title: 
  #   url: 
  # <table>
  #   <tr>
  #     <td> <a href="index.html"><span>English</span></a> </th>
  #     <td> <a href="index_j.html"><span>Japanese</span></a> </th>
  #   </tr>
  #   <tr>
  #     <td> <a href="./bio.html"><span>Biography </span></a> </td>
  #     <td> <a href="bio_j.html"><span>経歴</span></a> </td>
  #   </tr>
  #   <tr>
  #     <td> <a href="pub.html"><span>Publications</span></a> </td>
  #     <td> <a href="pub_j.html"><span>業績</span></a> </td>
  #   </tr>
  #   <tr>
  #     <td> <a href="proj.html"><span>Projects </span></a> </td>
  #     <td> <a href="proj_j.html"><span>プロジェクト</span></a> </td>
  #   </tr>
  #   <tr>
  #     <td colspan="2"> <a href="etc_j.html"><span>その他（勉強ノート・日記）</span></a> </td>
  #   </tr>
  # </table>
  # </font>
  # <font size="6"> 
  # <a href="/assets/files/CV.pdf"> Kentaro Uno </a>
  # </font>
  # <p><font size="4"> - Robotics Researcher</font></p> 
  # <span style="color:#333333"> Kentaro Uno </span> <p><font size="4"> -- Robotics Researcher</font></p>
# <font size="4"> <a href="index.html"><span>English</span></a> | <a href="index_j.html"><span>Japanese</span></a> <br> <a href="./bio.html"><span>Biography >>>> </span></a> | <a href="bio_j.html"><span>経歴</span></a> <br> <a href="pub.html"><span>Publications >> </span></a> | <a href="pub_j.html"><span>業績</span></a> <br> <a href="proj.html"><span>Projects >>>>>> </span></a> | <a href="proj_j.html"><span>プロジェクト</span></a> </font> <br><br> Kentaro Uno <p><font size="4"> - Robotics Researcher</font></p> 

logo: /assets/img/bio-photo-landscape.png

description: <p class="small"> I am a robotics researcher. My research interests are in the robotics in the harsh environment such as space and unstructured terrain. Feel free to download my <a href="/assets/files/CV.pdf">CV</a> (Contact info. is in it.). </p> 

# <p> My <a href="https://www.linkedin.com/in/unoken/" target="_blank">LinkedIn</a> is also available. </p>
# <div style="line-height:1em;"> xxxx </div> 
show_downloads:

google_analytics:

theme: jekyll-theme-minimal

bg_default: /assets/img/bg-default.jpg
