title: Home

menu:
  - title: Biography
    url: /bio.html
  - title: 研究経歴
    url: /bio_j.html
  
  - title: Publications
    url: /pub.html
  - title: 論文業績
    url: /pub_j.html

  # - title: Projects
  #   url: /proj.html

logo: /assets/img/bio-photo-landscape.png

description: <p class="small"> I am a robotics researcher. My research interests are in the robotics in the harsh environment such as space and unstructured terrain. Feel free to download my <a href="/assets/files/CV.pdf">CV</a> (Contact info. is in it.). </p> 

# <p> My <a href="https://www.linkedin.com/in/unoken/" target="_blank">LinkedIn</a> is also available. </p>
# <div style="line-height:1em;"> xxxx </div> 
show_downloads:

google_analytics: G-GL73SEZBBC

theme: jekyll-theme-minimal

bg_default: /assets/img/bg-default.jpg
